
services:
    
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel-cash
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token 
    networks:
      - firefly_iii
  integrator:
    image: ghcr.io/dvankley/firefly-plaid-connector-2:latest
    platform: linux/arm64
    hostname: plaidconnector
    volumes:
        - type: bind
          source: ./src/main/resources/application.yml
          target: /opt/fpc-config/application.yml
          read_only: true
    environment:
      - SPRING_CONFIG_LOCATION=/opt/fpc-config/application.yml
    networks:
      - firefly_iii

volumes:
   firefly_iii_upload:

networks:
  firefly_iii:
    driver: bridge
  
